version: '3'

services:
  reptiles-srv:
    image: reptiles-srv:latest
    restart: always
    volumes:
      - ./log/:/home/apple/app/log/
    depends_on:
      - mysql
      - redis
  mysql:
    restart: always
    image: mysql:5.6
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf/:/etc/mysql/conf.d
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=products
      - MYSQL_ROOT_PASSWORD=123456
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - reptiles-srv
    ports:
      - "8848:80"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: "redis-server"
    logging:
      options:
        max-size: 50m